services:
  tuw-autojoin:
    image: localhost/tuw-autojoin
    container_name: tuw-autojoin
    build: .
    restart: on-failure
    env_file: .env
    environment:
      LOGIN_USERNAME: '${LOGIN_USERNAME}'
      LOGIN_PASSWORD: '${LOGIN_PASSWORD}'
      URL: '${URL}'
      TRY_GROUPS: '${TRY_GROUPS}'
      PRELOGIN_SECOND: '${PRELOGIN_SECOND}'
      PRELOGIN_MINUTE: '${PRELOGIN_MINUTE}'
      PRELOGIN_HOUR: '${PRELOGIN_HOUR}'
      PRELOGIN_DATE: '${PRELOGIN_DATE}'
      PRELOGIN_MONTH: '${PRELOGIN_MONTH}'
      PRELOGIN_YEAR: '${PRELOGIN_YEAR}'
      PRELOGIN_TZ: '${PRELOGIN_TZ}'
      PRELOGIN_RETRY_INTERVAL: '${PRELOGIN_RETRY_INTERVAL}'
      PRELOGIN_RETRY_MAX: '${PRELOGIN_RETRY_MAX}'
      SIGNUP_SECOND: '${SIGNUP_SECOND}'
      SIGNUP_MINUTE: '${SIGNUP_MINUTE}'
      SIGNUP_HOUR: '${SIGNUP_HOUR}'
      SIGNUP_DATE: '${SIGNUP_DATE}'
      SIGNUP_MONTH: '${SIGNUP_MONTH}'
      SIGNUP_YEAR: '${SIGNUP_YEAR}'
      SIGNUP_TZ: '${SIGNUP_TZ}'
      SIGNUP_RETRY_INTERVAL: '${SIGNUP_RETRY_INTERVAL}'
      SIGNUP_RETRY_MAX: '${SIGNUP_RETRY_MAX}'
