services:
  tuw-autojoin:
    image: localhost/tuw-autojoin
    container_name: tuw-autojoin
    build: .
    restart: on-failure
    env_file: .env
    cap_add:
      - SYS_ADMIN
    environment:
      LOGIN_USERNAME: '${LOGIN_USERNAME}'
      LOGIN_PASSWORD: '${LOGIN_PASSWORD}'
      PRELOGIN_CRON: '${PRELOGIN_CRON}'
      PRELOGIN_TZ: '${PRELOGIN_TZ}'
      PRELOGIN_RETRY_INTERVAL: '${PRELOGIN_RETRY_INTERVAL}'
      PRELOGIN_RETRY_MAX: '${PRELOGIN_RETRY_MAX}'
      SIGNUP_URL: '${SIGNUP_URL}'
      SIGNUP_TRY_GROUPS: '${SIGNUP_TRY_GROUPS}'
      SIGNUP_CRON: '${SIGNUP_CRON}'
      SIGNUP_TZ: '${SIGNUP_TZ}'
      SIGNUP_RETRY_INTERVAL: '${SIGNUP_RETRY_INTERVAL}'
      SIGNUP_RETRY_MAX: '${SIGNUP_RETRY_MAX}'
